# Generated by Django 6.0.3 on 2026-04-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do destino"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="País")),
                (
                    "continent",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Continente"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(blank=True, max_length=10)),
                ("best_months", models.JSONField(blank=True, default=list)),
                (
                    "photo_upload",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="destinations/",
                        verbose_name="Foto (upload)",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, verbose_name="Foto (URL externa)"),
                ),
                (
                    "visa_required",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("visa_type", models.CharField(blank=True, max_length=100)),
                (
                    "vaccination_required",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("vaccines", models.JSONField(blank=True, default=list)),
                ("vaccines_notes", models.TextField(blank=True)),
                (
                    "other_requirements_title",
                    models.CharField(blank=True, max_length=100),
                ),
                ("other_requirements_description", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_description", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privado"),
                            ("restricted", "Restrito"),
                            ("public", "Público"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("active", "Ativo")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
                "ordering": ["-created_at"],
            },
        ),
    ]
