# Generated by Django 6.0.3 on 2026-04-06 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do destino"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="País")),
                (
                    "continent",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Continente"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de idiomas falados no destino.",
                        verbose_name="Idiomas falados",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Ex: BRL, USD, EUR",
                        max_length=10,
                        verbose_name="Moeda",
                    ),
                ),
                (
                    "best_months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de inteiros de 1 a 12.",
                        verbose_name="Melhores meses para visitar",
                    ),
                ),
                (
                    "visa_required",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Visto necessário",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Visto de turismo, E-visa, Visto on arrival.",
                        max_length=100,
                        verbose_name="Tipo de visto",
                    ),
                ),
                (
                    "vaccination_required",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Vacina necessária",
                    ),
                ),
                (
                    "vaccines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de códigos de vacinas obrigatórias.",
                        verbose_name="Vacinas necessárias",
                    ),
                ),
                (
                    "vaccines_notes",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes sobre as vacinas ou vacinas não listadas.",
                        verbose_name="Observações sobre vacinas",
                    ),
                ),
                (
                    "other_requirements_title",
                    models.CharField(
                        blank=True,
                        help_text="Ex: ETIAS, eTA, Registro de saúde.",
                        max_length=100,
                        verbose_name="Título da exigência",
                    ),
                ),
                (
                    "other_requirements_description",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Autorização de viagem obrigatória para entrada na Europa.",
                        verbose_name="Descrição da exigência",
                    ),
                ),
                ("photo_url", models.URLField(blank=True, verbose_name="URL da foto")),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="URL de origem"),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True,
                        help_text="Texto extraído da URL de origem (Instagram, blog, etc.).",
                        verbose_name="Descrição da fonte",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privado"),
                            ("restricted", "Restrito (usuários do app)"),
                            ("public", "Público"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("active", "Ativo")],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
                "ordering": ["-created_at"],
            },
        ),
    ]
