# Generated by Django 6.0.3 on 2026-04-06 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="photo_upload",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="destinations/",
                verbose_name="Foto (upload)",
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="best_months",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="destination",
            name="currency",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="destination",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="destination",
            name="other_requirements_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="other_requirements_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="destination",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="Foto (URL externa)"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="source_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="status",
            field=models.CharField(
                choices=[("draft", "Rascunho"), ("active", "Ativo")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="vaccination_required",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="vaccines",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="destination",
            name="vaccines_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="visa_required",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="visa_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="destination",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Privado"),
                    ("restricted", "Restrito"),
                    ("public", "Público"),
                ],
                default="private",
                max_length=20,
            ),
        ),
    ]
