# Generated by Django 6.0.3 on 2026-04-06 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Como você quer ser chamado pelos outros usuários. Se não preencher, usaremos seu nome completo.",
                        max_length=80,
                        verbose_name="Nome público",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BR", "🇧🇷 Brasil"),
                            ("PT", "🇵🇹 Portugal"),
                            ("US", "🇺🇸 Estados Unidos"),
                            ("AR", "🇦🇷 Argentina"),
                            ("ES", "🇪🇸 Espanha"),
                            ("FR", "🇫🇷 França"),
                            ("DE", "🇩🇪 Alemanha"),
                            ("IT", "🇮🇹 Itália"),
                            ("JP", "🇯🇵 Japão"),
                            ("CN", "🇨🇳 China"),
                            ("MX", "🇲🇽 México"),
                            ("CO", "🇨🇴 Colômbia"),
                            ("CL", "🇨🇱 Chile"),
                            ("OTHER", "Outro"),
                        ],
                        help_text="Usada para sugerir automaticamente informações de visto para cada destino que você catalogar.",
                        max_length=10,
                        verbose_name="Nacionalidade",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Aparece no seu perfil público e nos roteiros compartilhados.",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["-created_at"],
            },
        ),
    ]
