# Generated by Django 6.0.3 on 2026-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_change_token",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="E-mail pendente"
            ),
        ),
    ]
