# Generated by Django 6.0.3 on 2026-04-14 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Dia")),
                ("data", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "titulo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Título do dia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia",
                "verbose_name_plural": "Dias",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Indicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("turismo", "Ponto Turístico"),
                            ("atividade", "Atividade"),
                            ("restaurante", "Restaurante"),
                            ("cafe", "Café"),
                            ("mercado", "Mercado"),
                            ("outro", "Outro"),
                        ],
                        default="turismo",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "horario_sugerido",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário sugerido"
                    ),
                ),
                (
                    "custo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo estimado (moeda local)",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "dia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicacoes",
                        to="roteiros.dia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicação",
                "verbose_name_plural": "Indicações",
                "ordering": ["ordem", "horario_sugerido"],
            },
        ),
        migrations.CreateModel(
            name="Roteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privado"),
                            ("restricted", "Restrito"),
                            ("public", "Público"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "custo_hospedagem",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo total de hospedagem (moeda local)",
                    ),
                ),
                (
                    "custo_alimentacao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo total de alimentação (moeda local)",
                    ),
                ),
                (
                    "taxa_cambio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Ex: se 1 USD = 5,20 BRL, informe 5.20",
                        max_digits=10,
                        null=True,
                        verbose_name="Taxa de câmbio (moeda local → BRL)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "copiado_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copias",
                        to="roteiros.roteiro",
                        verbose_name="Copiado de",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiros",
                        to="destinations.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteiro",
                "verbose_name_plural": "Roteiros",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="dia",
            name="roteiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dias",
                to="roteiros.roteiro",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dia",
            unique_together={("roteiro", "numero")},
        ),
    ]
