# Generated by Django 6.0.3 on 2026-04-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeaturedDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do destino"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="País")),
                (
                    "continent",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Continente"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="Slug (URL)"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(blank=True, default=list, verbose_name="Idiomas"),
                ),
                (
                    "currency",
                    models.CharField(blank=True, max_length=10, verbose_name="Moeda"),
                ),
                (
                    "best_months",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Melhores meses"
                    ),
                ),
                (
                    "photo_upload",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="featured/",
                        verbose_name="Foto (upload)",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, verbose_name="Foto (URL externa)"),
                ),
                (
                    "visa_required",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Visto necessário",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de visto"
                    ),
                ),
                (
                    "vaccination_required",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Vacina necessária",
                    ),
                ),
                (
                    "vaccines",
                    models.JSONField(blank=True, default=list, verbose_name="Vacinas"),
                ),
                (
                    "vaccines_notes",
                    models.TextField(blank=True, verbose_name="Obs. vacinas"),
                ),
                (
                    "other_requirements_title",
                    models.CharField(blank=True, max_length=100),
                ),
                ("other_requirements_description", models.TextField(blank=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição do destino"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de exibição"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Destino em Destaque",
                "verbose_name_plural": "Destinos em Destaque",
                "ordering": ["order", "name"],
            },
        ),
    ]
