# Generated by Django 6.0.3 on 2026-04-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da lista')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('emoji', models.CharField(blank=True, default='📍', max_length=8, verbose_name='Emoji')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('list_type', models.CharField(choices=[('manual', 'Manual'), ('smart', 'Inteligente')], default='manual', max_length=20, verbose_name='Tipo')),
                ('smart_criteria', models.JSONField(blank=True, default=dict, verbose_name='Critérios inteligentes')),
                ('visibility', models.CharField(choices=[('private', 'Privada'), ('restricted', 'Restrita'), ('public', 'Pública')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de destinos',
                'verbose_name_plural': 'Listas de destinos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='destinations.destination')),
                ('destination_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='lists.destinationlist')),
            ],
            options={
                'verbose_name': 'Item da lista',
                'verbose_name_plural': 'Itens da lista',
                'ordering': ['position', 'added_at'],
                'unique_together': {('destination_list', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='destinationlist',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='lists', through='lists.ListItem', to='destinations.destination'),
        ),
    ]
